server.port: 8000

input:
  dir: uploaded/
output:
  dir: output/
  summary-header: Client Id, Transaction Type, Transaction Date, Priority, Processing Fee
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      # path: /h2console/
  datasource:
    url: jdbc:h2:file:~/testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
processing-fee:
  priority: 500
  intraday: 10
  normal:
    sell: 100
    withdraw: 100
    buy: 50
    deposit: 50